using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EstudoReact.Data.Migrations
{
    /// <inheritdoc />
    public partial class InsercaoEstado : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"INSERT INTO ESTADO VALUES('ACRE')
INSERT INTO ESTADO VALUES('ALAGOAS')
INSERT INTO ESTADO VALUES('AMAPA')
INSERT INTO ESTADO VALUES('AMAZONAS')
INSERT INTO ESTADO VALUES('BAHIA')
INSERT INTO ESTADO VALUES('CEARA')
INSERT INTO ESTADO VALUES('DISTRITO FEDERAL')
INSERT INTO ESTADO VALUES('ESPIRITO SANTO')
INSERT INTO ESTADO VALUES('GOIAS')
INSERT INTO ESTADO VALUES('MARANHAO')
INSERT INTO ESTADO VALUES('MATO GROSSO')
INSERT INTO ESTADO VALUES('MATO GROSSO DO SUL')
INSERT INTO ESTADO VALUES('MINAS GERAIS')
INSERT INTO ESTADO VALUES('PARA')
INSERT INTO ESTADO VALUES('PARAIBA')
INSERT INTO ESTADO VALUES('PARANA')
INSERT INTO ESTADO VALUES('PERNAMBUCO')
INSERT INTO ESTADO VALUES('PIAUI')
INSERT INTO ESTADO VALUES('RIO DE JANEIRO')
INSERT INTO ESTADO VALUES('RIO GRANDE DO NORTE')
INSERT INTO ESTADO VALUES('RIO GRANDE DO SUL')
INSERT INTO ESTADO VALUES('RONDONIA')
INSERT INTO ESTADO VALUES('RORAIMA')
INSERT INTO ESTADO VALUES('SANTA CATARINA')
INSERT INTO ESTADO VALUES('SAO PAULO')
INSERT INTO ESTADO VALUES('SERGIPE')
INSERT INTO ESTADO VALUES('TOCANTINS')");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
